### ISSUE TITLE
Notice: Undefined index: value in vendor\level-2\transphporm\src\Hook\Formatter.php on line 25

### ISSUE THREAD

**Issue by Jacco-V** [Level-2/Transphporm#169] opened 2017-09-24 16:26 UTC
Hi,

I'm paying around with the [Building an entire page](https://github.com/Level-2/Transphporm/wiki/Building-an-entire-page) examples.

I've an imported `base.tss` files, which works fine:
```css
footer span {
	content: "now";
	format: date "Y"}
```

However, If I change the above into:
```css
footer span {
	content: "now";
	format: date "Y"
}
```
I get the following error:
![capture](https://user-images.githubusercontent.com/19333579/30784453-921ae704-a155-11e7-8d2f-a60c7819da84.PNG)
(the `.tss` file has Unix new lines)

Which I suspect should be classified as a bug?

**Comment by solleer** [comment] 2017-10-16 15:55
The issue is probably that there is no semicolon at the end of the last rule.

**Comment by garrettw** [comment] 2017-10-16 16:57
@solleer That's not the point. Clearly his first example, which is also missing the semicolon, works fine.

**Comment by solleer** [comment] 2017-10-16 17:23
The format interpreter just looks at the tokens so it sees a new line as needing to be interpreted but there is no value index set for it hence the error. Technically it should work without the semicolon though since it is the last rule, so I will look into fixing it.

**Comment by solleer** [comment] 2017-10-16 17:37
I can't seem to duplicate the problem. This test passes:
```php
public function testNewLineAfterFormatterNoSemicolon() {
    $xml = '<div></div>';

$tss = "
div {
    content: 'now';
    format: date 'Y'
}
	";

	$template = new \Transphporm\Builder($xml, $tss);

	$this->assertEquals($this->stripTabs('<div>2017</div>'),
		$this->stripTabs($template->output()->body));
}
```

**Comment by solleer** [comment] 2017-10-27 11:39
@Jacco-V I can't reproduce this error

**Comment by Jacco-V** [comment] 2017-10-28 12:49
I have the following files:

`index.php`
```php
<?php
require_once(__DIR__ . '../vendor/autoload.php');

$data = [
    'title' => 'Home',
    'page' => 'home.xml'
];

$transphporm = new \Transphporm\Builder('layout.html', 'layout.tss');
echo $transphporm->output($data)->body;
```

`layout.html`
```html
<!DOCTYPE HTML>
<html>
	<head>
		<title>My Website</title>
	</head>
	<body>
		<header>
			Header
		</header>

		<nav>
			<ul>
				<li><a href="/">Home</a></li>
				<li><a href="/about.html">About</a></li>
				<li><a href="/contact.html">Contact</a></li>
			</ul>
		</nav>

		<main>
			Main content block
		</main>
		
		<footer>
			Copyright <span>year</span>
		</footer>
	</body>
</html>
```

`home.xml`
```xml
<?xml version="1.0"?>
<template>
	<p>Welcome to this example</p>
</template>
```

`layout.tss`
```css
title {
	content: data(title);
}

main {
	content: template(data(page));
}

footer span {
	content: "now";
	format: date "Y"
}
```

**Comment by TomBZombie** [comment] 2017-12-08 18:07
This has been fixed in a recent commit, I will draft a new release shortly.

**Closed** 2017-12-08 18:12 UTC
