### ISSUE TITLE
Cache Issues

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#109] opened 2016-07-04 18:41 UTC
- [x] Using functions when verifying an attr (ex: `a[href=data(link)]`)
- [x] Imported files not loaded when updated
- [x] Attribute changes like `#menu a[href=data(url)]:attr(class) { content: 'active'; }` persist through different page loads

**Comment by solleer** [comment] 2016-07-04 23:58
There are lots of issues with caching. Enough to make it unusable

**Comment by solleer** [comment] 2016-07-05 01:38
It would be best if all the normal tests were somehow run in a way to test caching too. Like having them run each test twice with the same cache.

**Comment by solleer** [comment] 2016-10-20 00:39
Since Sheet is really big right now maybe there should be a TssCache class that handles more of the specific in caching that are in sheet right now. The TssCache class could accept the Cache class in its constructor

**Comment by solleer** [comment] 2016-10-20 00:46
or it could be called SheetCache

**Comment by solleer** [comment] 2016-11-01 09:37
I can't get this test to pass
```php
public function testCacheWithAttribute() {

	$xml = $this->makeXml('<div>
		<span data-hide="1">Test1</span>
		<span data-hide="2">Test2</span>
		</div>');

	$tss = $this->makeTss('
			span[data-hide=data(hide)] { display:none; }');

	$cache = new \ArrayObject();

	$template = new \Transphporm\Builder($xml, $tss);
	$template->setCache($cache);

	$expectedOutput = $this->stripTabs('<div><span data-hide="2">Test2</span></div>');
	$this->assertEquals($this->stripTabs($template->output(['hide' => 1])->body), $expectedOutput);

	$template = new \Transphporm\Builder($xml, $tss);
	$template->setCache($cache);
	var_dump($cache);

	$expectedOutput = $this->stripTabs('<div><span data-hide="1">Test1</span></div>');

	// Run output again
	$this->assertEquals($expectedOutput, $this->stripTabs($template->output(['hide' => 2])->body));
}
```

**Comment by solleer** [comment] 2016-11-01 15:36
The problem is that the transphporm attribute to remove is never removed so I think the xml needs to be cached earlier

**Comment by solleer** [comment] 2016-11-01 17:51
This test passes
```php
public function testCacheWithAttribute() {

    $xml = $this->makeXml('<div>
        <span data-hide="1">Test1</span>
        <span data-hide="2">Test2</span>
        </div>');

    $tss = $this->makeTss('
            span {display: show;}
            span[data-hide=data(hide)] { display:none; }');

    $cache = new \ArrayObject();

    $template = new \Transphporm\Builder($xml, $tss);
    $template->setCache($cache);

    $expectedOutput = $this->stripTabs('<div><span data-hide="2">Test2</span></div>');
    $this->assertEquals($this->stripTabs($template->output(['hide' => 1])->body), $expectedOutput);

    $template = new \Transphporm\Builder($xml, $tss);
    $template->setCache($cache);
    var_dump($cache);

    $expectedOutput = $this->stripTabs('<div><span data-hide="1">Test1</span></div>');

    // Run output again
    $this->assertEquals($expectedOutput, $this->stripTabs($template->output(['hide' => 2])->body));
}
```
The problem is there must be a statement to reset any displays

**Comment by solleer** [comment] 2016-11-01 17:59
@TomBZombie I don't know of a good way to have transphporm reset the display only when applicable

**Comment by solleer** [comment] 2017-03-13 17:56
@TomBZombie Can you work on the cache issues?

**Comment by TomBZombie** [comment] 2017-03-14 13:16
Yes, that's the next thing on my list. We may need to add some more markers in the XML to allow transphporm to correctly replace/update the values at the right time

**Comment by TomBZombie** [comment] 2017-03-16 17:39
Re: testCacheWithAttribute

Really, you'd need the following tss:

```
    $tss = $this->makeTss('
    		span {display: block;  update-frequency: always }
            span[data-hide=data(hide)] { display: none; update-frequency: always }');

```

It may be worth automatically setting `update-frequency` to `always` if `display` is present, although that could cause other issues.

In principle, the code above should work as regardless of cache, it should first set the two spans to `show` then set one to `remove`. The problem, however, is not the `display` function. The wrong element is actually getting selected. I think `span[data-hide=data(hide)]` must be caching the `data()` lookup as the `display` function always get's passed the `<span data-hide="1">Test1</span>` element. 

I need to look into it further, but I  fixed a bug in valueparser that makes debugging easier. Try this:

```php
    $tss = $this->makeTss('
    		span {display: block first data(hide);  update-frequency: always }
            span[data-hide=data(hide)] { display: none second data(hide); update-frequency: always }');


```

Then in `Display.php` you can check the `$values` array to see if `data(hide)` is correct:

```
		$element->removeAttribute('transphporm');
		if ($pseudoMatcher->hasFunction('attr')) $element->removeAttribute($pseudoMatcher->getFuncArgs('attr')[0]);
		else if (strtolower($values[0]) === 'none') $element->setAttribute('transphporm', 'remove');
		else $element->setAttribute('transphporm', 'show');

		var_dump($values);
		var_dump($element->ownerDocument->saveXml());

```

It's right at this point, the problem is, `$element` is wrong.

**Comment by TomBZombie** [comment] 2017-03-16 18:07
After more digging I've found the source of the problem but I'm not sure how to fix it, the problem is the static `processAttr` function in `CSSToXpath`:

```
	//XPath only allows registering of static functions... this is a hacky workaround for that
	public static function processAttr($attr, $element, $hash) {
		$attr = unserialize(base64_decode($attr));
		
		var_dump("\n\n\n\n\n\n" . md5($hash));
		var_dump($element[0]->ownerDocument->saveXml($element[0]));
		/*foreach (self::$instances as $instance) {
			var_dump($instance->functionSet->elementData);
		}*/
		$functionSet = self::$instances[$hash]->functionSet;
		$functionSet->setElement($element[0]);

		$attributes = array();
        foreach($element[0]->attributes as $attribute_name => $attribute_node) {
            $attributes[$attribute_name] = $attribute_node->nodeValue;
        }	

       
       // var_dump($functionSet->elementData);
        $parser = new \Transphporm\Parser\Value($functionSet, true);
		$return = $parser->parseTokens($attr, $attributes);

		return $return[0] === '' ? false : $return[0];
	}

```

For some reason, with the cache enabled, it always gets passed the same value for `$hash`, which means it uses the wrong `functionSet` instance, which, in turn, has the wrong `elementData` instance. I can't figure out why the cache is affecting it at all. Both `CSSToXpath` instances are being created, but it always uses the same one.

**Comment by solleer** [comment] 2017-06-21 18:15
There are still cache issues to be fixed

**Comment by TomBZombie** [comment] 2017-12-08 16:54
Can you add tests or describe any cache issue which still exist? I'm starting a new project with transphporm so hopefully will encounter them myself but if you have any examples to hand it would be nice to fix them sooner rather than later

**Comment by solleer** [comment] 2017-12-09 02:55
Attribute changes like `#menu a[href=data(url)]:attr(class) { content: 'active'; }` persist through different page loads

**Comment by TomBZombie** [comment] 2017-12-09 19:30
In that specific case you would need `update-frequency: always` to change on each page view. However, I can see that sometimes this may be an issue. I'll try to write a test case for it.

**Comment by TomBZombie** [comment] 2017-12-09 20:04
We actually fixed that quite some time ago (can't remember if it was you or me), I'll mark it off in this issue.

The way it's done at the moment is `:attr()` attributes are always reset. From a performance perspective that may not be the best way to do it and we might want to look at an alternative approach, but the upside is that this works:

```php

	public function testCacheAttributeChange() {

		$xml = '<div></div>';

		//Set the div's class to "loggedin" if the user is logged in
		$tss = 'div:data[loggedin=true]:attr(class) {content: "loggedin"}';

		$template = new \Transphporm\Builder($xml, $tss);
		$cache = new \ArrayObject();
		$template->setCache($cache);


		//Start by assuming they are logged in
		$output1 = $template->output(['loggedin' => true])->body;

		//And the class should be set when the page is displayed
		$this->assertEquals($this->stripTabs('<div class="loggedin"></div>'), $this->stripTabs($output1));



		//Expire the cache by advancing time 10 minutes
		$date = new \DateTime();
		$date->modify('+11 minutes');
		
		$template->setTime($date->format('U'));


		//On the next page load, display the page again
		$template = new \Transphporm\Builder($xml, $tss);
		$template->setCache($cache);
		
		//This time, when the page loads, they are logged out
		$output2 = $template->output(['loggedin' => false])->body;

		//And the class should not be set
		$this->assertEquals($this->stripTabs('<div></div>'), $this->stripTabs($output2));

	}
```

I'm going to close this for now, if there are any remaining issues, we'll need some tests to handle them.

**Closed** 2017-12-09 20:07 UTC
Labels: bug
