### ISSUE TITLE
How to handle multidimensional arrays

### ISSUE THREAD

**Issue by hobbeshunter** [Level-2/Transphporm#46] opened 2016-01-24 12:23 UTC
I have an array that represents the structure of a menu:
```
[
  {
    "target":"page_56695eb1d2f72",
    "title":"Test",
    "children":
      [
        {
          "target":"page_56698dac23118",
          "title":"Test 2",
          "children":
            [
              {
                 "target":"page_568541006e802",
                 "title":"Test 3"
               }
             ]
          }
      ]
  },
  {
     "target":"http://facebook.com",
     "title":"Facebook"
  }
]
```
What I want is something like:
```html
<ul>
  <li>
    <a href="page_56695eb1d2f72">Test</a>
    <ul>
       <li>
         <a href="page_56698dac23118">Test 2</a>
         <ul>
           <li>
             <a href="page_568541006e802">Test 3</a>
           </li>
         </ul>
       </li>
    </ul>
  </li>
  <li>
    <a href="http://facebook.com">Facebook</a>
  </li>
</ul>
```
But I can't figure out any possible way to express this in tss conditions.

**Comment by TomBZombie** [comment] 2016-01-25 17:28
This isn't a complete fix by any means and I think this is related to #41 but I've added a sort of fix for this. 

What's really needed here is infinite recursion. And now, this works:



```css
ul li {repeat: data(children); bind: iteration())}
ul li:iteration[children]:after {content: template(tests/nav.xml)}

ul li a:attr(href) {content: iteration(target);}
ul li a {content: iteration(title);}


```

```xml
<?xml version="1.0"?>
<template>

	<ul>
  		<li>
    		<a href=""></a>
    	</li>  	

    </ul>
</template>
```

With the data:

```php
		$data = json_decode('{ "children": [
  {
    "target":"one",
    "title":"Test 1",
    "children":
      [
        {
          "target":"two",
          "title":"Test 2",
          "children":
            [
              {
                 "target":"two.1",
                 "title":"grandchild 1"
               },
               {
                 "target":"two.2",
                 "title":"grandchildchild 2"
               }
             ]
          },
          {
     "target":"child 1",
     "title":"child 1"
  }
      ]
  },
  {
     "target":"http://facebook.com",
     "title":"Facebook"
  }
]}', true);
```

This isn't quite the same data structure you had but it produces the output:

```
<ul>
                <li>
                <a href="one">Test 1</a>


    

        <ul>
                <li>
                <a href="two">Test 2</a>


    

        <ul>
                <li>
                <a href="two.1">grandchild 1</a>


        </li><li>
                <a href="two.2">grandchildchild 2</a>


        </li>

    

    </ul>
</li><li>
                <a href="child 1">child 1</a>


        </li>

    

    </ul>
</li><li>
                <a href="http://facebook.com">Facebook</a>


        </li>

    

    </ul>
```

This isn't quite what you wanted but works with a single `<ul>` template to support unlimited nesting. I need to tweak it to support it without wrapping the original data in an array called "children".

I'll explain how the TSS works when I get a chance! But hopefully you can see what it's doing.

**Comment by TomBZombie** [comment] 2016-01-25 21:58
Having thought about it more, unfortunately this approach won't work as intended. Although the above case works, it won't work if the TSS is more specific e.g. `nav ul li` and only the ul is in the template

**Comment by hobbeshunter** [comment] 2016-01-30 21:47
ouh. that broke a lot :D I had to go a version back

**Comment by TomBZombie** [comment] 2016-02-26 18:31
I've tried a lot of different things to get this to work and it always has side-effects somewhere. In theory what needs to happen when template() is called:

- Load the template into the document
- Re-run TSS on new elements

The problem with  this, of course, is that as above, the TSS rule might be:

```php
nav { content: template('nav.xml');
nav ul li {repeat: data(children); }
```

You can't just apply the above TSS to nav.xml because `nav ul li` won't match anything (as it only contains the ul tag onwards)

My next thought was to re-apply the entire TSS to the entire document, however, this causes its own big set of problems because it involves keeping  track of which elements have had which rules applied to them so it can only be applied to the "new" elements. Doing this, causes numerous problems with caching.

I'll have to think about this further as it would be  better to be able to do this.

**Comment by TomBZombie** [comment] 2016-02-27 15:04
I've somewhat got this working, however it breaks support for

```
div:before {content: template('foo.xml'); }
```

It causes the content to  be duplicated and I've spent some time working on a fix... it's not a simple task because in some cases you want the recursion and in others you don't.

**Comment by TomBZombie** [comment] 2016-02-27 16:04
Ok the only way I could do this is to force the TSS author to specify whether or not the TSS is re-applied to the imported template. This is done using

```css
div {content: template('foo.xml'); template-recursion: on}
```

When `template-recursion` is set to `on`, then the parent TSS file is re-applied to the included template.

rules such as `nav ul li` will also work because the rules are (effectively) applied after the template has been loaded into the document.

**Comment by TomBZombie** [comment] 2016-02-28 21:52
After the discussion here: https://github.com/Level-2/Transphporm/commit/2d04cd790c9888c0dcf27f4d9dbcca602c5ab85c#commitcomment-16373143 I have changed the way this works. To recursively apply a TSS file to an included template you must specify it. This is done using a third argument to the `template()` function supplying the TSS which is to be applied to the template as it's loaded. 

In this case,  the included file is run on the included template. By referencing itself it's possible to have a TSS include a template recursively.

nav.tss

```css
ul li {repeat: data(children); bind: iteration())}
ul li:iteration[children]:after {content: template('nav.xml', '', 'nav.tss'); }

ul li a:attr(href) {content: iteration(target);}
ul li a {content: iteration(title);}
```

**Comment by hobbeshunter** [comment] 2016-02-29 10:17
Sounds great to me. Can you provide an example or better a wiki page?

**Comment by TomBZombie** [comment] 2016-02-29 11:26
Take a look at the unit test, I used pretty much your exact example:

```php
	public function testNestedData() {
		        $data = json_decode('{ "children": [
  {
    "target":"Parent",
    "title":"Parent",
    "children":
      [
        {
          "target":"Child 2",
          "title":"Child 2",
          "children":
            [
              {
                 "target":"two.1",
                 "title":"grandchild 1"
               },
               {
                 "target":"two.2",
                 "title":"grandchildchild 2"
               }
             ]
          },
          {
     "target":"child 1",
     "title":"child 1"
  }
      ]
  },
  {
     "target":"http://facebook.com",
     "title":"Facebook"
  }
]}', true);

	  
	  $template = new \Transphporm\Builder(__DIR__ . '/nav.xml', __DIR__ . '/nav.tss');

	   $this->assertEquals($this->stripTabs('<ul>
				<li>
					<a href="Parent">Parent</a>
					<ul>
						<li>
							<a href="Child 2">Child 2</a>
							<ul>
								<li>
									<a href="two.1">grandchild 1</a>
								</li>
								<li>
									<a href="two.2">grandchildchild 2</a>
								</li>
							</ul>
						</li>
						<li>
							<a href="child 1">child 1</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="http://facebook.com">Facebook</a>
				</li>
	</ul>'), $this->stripTabs($template->output($data)->body));
	}

}


```

You'll see that I changed the format of `data` slightly so there is *always* a `children` element when the li is to be generated:

```php
  $data = json_decode('{ "children": [
  {
    "target":"Parent",
    "title":"Parent",
    "children":
      [
        {
          "target":"Child 2",

```

When the template is loaded, the li is repeated for each `data(children)` and the data bound using `bind` to the `iteration()`

```php
ul li {repeat: data(children); bind: iteration())}
```
The next line:

```php
ul li:iteration[children]:after {content: template('nav.xml', '', 'nav.tss'); }

```
Says, "If the current iteration has a `children` property, set the `:after` content to load `nav.xml` again. When `nav.xml` is loaded, it re-runs `nav.tss` and because the `li` element has had it's data bound to `iteration()` when the template is loaded, it's data is the children of the current iteration.

Finally it sets the content of the a element and it's href:

```php
ul li a:attr(href) {content: iteration(target);}
ul li a {content: iteration(title);}
```

**Closed** 2016-03-05 14:50 UTC

**Comment by hobbeshunter** [comment] 2016-03-17 15:16
Could you explain ´´´template('nav.xml', '', 'nav.tss');´´´, please. I tried to pass a .tss file as a third parameter to the template function, but it didn't do anything. Or is it just meant to work in combination with bind?
