### ISSUE TITLE
Regression between  319ec0fec6 and da7c375541

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#192] opened 2018-05-02 18:26 UTC
I had been running on commit 319ec0fec6 and updated yesterday to da7c375541, and found part of my XML template no longer getting animated (content) by my TSS.  No errors were thrown.

I wrote a simple test case, but it works, so there's some side effect going on that's catalyzed by the larger template arrangement.  I'm building from partials, so it's fairly complex.  The basic TSS rule which is failing, however, is this:
```css
widget {
    content: template(attr(href));
    content-mode: replace;
}
```
Where it replaces any `<widget>` XML elements with the XML template file specified in that element's `href` attribute, for example:
```xml
<widget href="payer-picker.xml">this content should be replace</widget>
```

I will continue to pursue finding a simpler test case which reproduces the problem which is significantly smaller than my actual usage.  ;-)

**Comment by cxj** [comment] 2018-05-03 03:25
In fact, that commit gives me a stack trace, although some number of commits later, the stack trace goes away and it just fails silently.  Here's the stack trace:
```
PHP Fatal error:  Uncaught Error: Call to undefined method DOMComment::getAttribute() in /Users/chris/test.templates/vendor/level-2/transphporm/src/Property/Content.php:91
Stack trace:
#0 /Users/chris/test.templates/vendor/level-2/transphporm/src/Property/Content.php(25): Transphporm\Property\Content->replaceContent(Object(DOMElement), Array)
#1 /Users/chris/test.templates/vendor/level-2/transphporm/src/Hook/PropertyHook.php(67): Transphporm\Property\Content->run(Array, Object(DOMElement), Array, Object(Transphporm\Hook\PseudoMatcher), Array)
#2 /Users/chris/test.templates/vendor/level-2/transphporm/src/Hook/PropertyHook.php(52): Transphporm\Hook\PropertyHook->callProperty('content', Object(DOMElement), Array)
#3 /Users/chris/test.templates/vendor/level-2/transphporm/src/Hook/PropertyHook.php(40): Transphporm\Hook\PropertyHook->callProperties(Object(DOMElement))
#4 /Users/chris/test.templates/vendor/level-2/transphporm/src/Template.php(70): Transphporm\Hook\PropertyHook->run(Object(DOMElement))
#5 /Users/chris/test.templates/v in /Users/chris/test.templates/vendor/level-2/transphporm/src/Property/Content.php on line 91
```

**Comment by cxj** [comment] 2018-05-03 03:31
So, in oldest to newest order:
- b5a6278c97c23c3e468e66bc1cf27ca18a46b798 and earlier work correctly.
- a3c2e5ba331483c8d6d13873c261cfd12e2a2ff5 through 04a4d124f2d95e4a48a44ba4120974d6b80e2247 cause a stack trace.
- 1bb4b5dd2173dc344bcf66b4f5f9d7e0d91e6a52 through HEAD fail silently.

**Comment by cxj** [comment] 2018-05-03 03:36
My primary TSS file:
```css
title {
    content: "My Title";
}

@import "navigation.tss";
nav {
    content: template("navigation.xml");
}

main {
    content: template("basic-elig-form.xml");
}

@import "widget/insert-widget.tss";

jslibs {
    content:
    "
<script src='/res/js/bootstrap-datepicker.min.js'></script>
    ";

    format: html;
    content-mode: replace;
}

#modal-right .modal-title {
    content: "Select a payer";
}
```

**Comment by cxj** [comment] 2018-05-03 03:39
My primary XML file:
```xml
<!DOCTYPE html>
<html xml:lang="en" lang="en">
<head>
    <title>Default Title</title>
    <meta charset="utf-8"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="/res/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/res/css/bootstrap-theme.css"/>
</head>
<body>
<header class="container">
    <!-- Top bar -->
    <div class="row">
            <nav>
                <!-- actual navigation menus get placed here -->
            </nav>
    </div>
</header>
<main class="container">
    <!-- main content gets placed here -->
</main>
<footer class="footer">
    <p>
        <small>Copyright &#169; 1999 - 2018 My Company</small>
    </p>
</footer>
<script src="/res/js/jquery/jquery.min.js"></script>
<script src="/res/js/bootstrap.min.js"></script>
<jslibs>
    <!-- One or more JS libraries -->
</jslibs>
</body>
</html>
```

**Comment by cxj** [comment] 2018-05-03 03:43
I still do not have a simple test to replicate the error.  The above primary files are just 2 of the 7 template files involved, included either via `@import` or `content: template();`.

**Comment by cxj** [comment] 2018-05-03 04:10
Here's a demonstration test case.  This works with commit b5a6278c97c23c3e468e66bc1cf27ca18a46b798 and fails with all later commits:
```php
<?php
require "vendor/autoload.php";
$tss = '
main {
    content: template("basic-elig-form.xml");
}
@import "insert-widget.tss";
';
$xml = '
<!DOCTYPE html>
<html xml:lang="en" lang="en">
<head></head>
<body> <main>..main..</main> </body>
</html>
';
$tpl = new Transphporm\Builder($xml, $tss);
echo $tpl->output([])->body . PHP_EOL;
```

File `basic-elig-form.xml`:
```xml
<div class="basic-elig-form container-fluid">
    <widget href="payer-picker.xml">p1</widget>
</div>
```

File `insert-widget.tss`:
```css
widget {
    content: template(attr(href));
    content-mode: replace;
}
```

File `payer-picker.xml`:
```xml
<p> Just some proof text to show that the widget tag got replaced </p>
```

**Comment by TomBZombie** [comment] 2018-05-03 14:13
Thanks or the simplified example. My initial thought is that it's an issue with running rules in the wrong order. If the rule for `widget` was executed before the rule for `main` then the `widget` element will not get replaced

**Comment by TomBZombie** [comment] 2018-05-03 15:17
Take a look at the latest commit, this should be fixed. As I suspected, the rules were being executed in the wrong order.

**Comment by cxj** [comment] 2018-05-03 19:34
The fix works for my simple test case, but fails for the full page with a stack trace, included below. 
```
Error: Call to undefined method DOMComment::getAttribute() in /Users/chris/test/vendor/level-2/transphporm/src/Property/Content.php on line 92

Call Stack:
1. {main}() /Users/chris/test/templates/widget.php:0
2. Transphporm\Builder->output() /Users/chris/test/templates/widget.php:10
3. Transphporm\Template->output() /Users/chris/test/vendor/level-2/transphporm/src/Builder.php:66
4. Transphporm\Template->processHooks() /Users/chris/test/vendor/level-2/transphporm/src/Template.php:85
5. Transphporm\Hook\PropertyHook->run() /Users/chris/test/vendor/level-2/transphporm/src/Template.php:70
6. Transphporm\Hook\PropertyHook->callProperties() /Users/chris/test/vendor/level-2/transphporm/src/Hook/PropertyHook.php:40
7. Transphporm\Hook\PropertyHook->callProperty() /Users/chris/test/vendor/level-2/transphporm/src/Hook/PropertyHook.php:52
8. Transphporm\Property\Content->run() /Users/chris/test/vendor/level-2/transphporm/src/Hook/PropertyHook.php:67
9. Transphporm\Property\Content->replaceContent() /Users/chris/test/vendor/level-2/transphporm/src/Property/Content.php:25
```

**Comment by TomBZombie** [comment] 2018-05-04 11:07
The error there is relating to an XML comment, can you paste the file that contains comments? Is it valid XML or does it use HTML? Is the comment at the very top of the file?

**Comment by TomBZombie** [comment] 2018-05-04 11:47
I've managed to replicate the issue. The problem is when a comment is at the root level of a template file. looking at this we'll need to filter out these comments when `content-mode` is set to `replace`, otherwise if it's cached, each time the cache is refreshed it will add add the comment to the document.

**Comment by TomBZombie** [comment] 2018-05-04 12:07
Try the latest commit, it solves the issue with comments at the root level of a template included using `content-mode: replace`

**Comment by cxj** [comment] 2018-05-04 14:10
My initial testing looks good.  I'm going to be sure I can toggle between fail and success via the last two commits to be sure.

**Comment by TomBZombie** [comment] 2018-05-04 14:25
No, at the moment any comment that is at the top of an included template, when using `content-mode: replace` will be removed from the final output to avoid duplication each time the cache is updated.

If needed I could add some logic to find duplicated comments and remove duplicates so the original comments appears in the output but the overhead seems unnecessary for functionality that probably isn't needed.

**Comment by cxj** [comment] 2018-05-04 15:25
Right.  In fact, I prefer to have no comments at all in my output.  They're only there for forgetful developers like me.  ;-)

**Comment by cxj** [comment] 2018-05-04 15:26
Thank you very much for the quick fixes.  It's much appreciated.  Transphporm has really made our web development so much easier to build and maintain.

**Comment by TomBZombie** [comment] 2018-05-07 15:29
Thanks! I'm glad you're finding it useful. Can I put your quote " Transphporm has really made our web development so much easier to build and maintain." in the readme?  It might get a few more people to give it a try

**Comment by garrettw** [comment] 2018-05-07 16:16
Agreed, that testimonial is pure gold 😄

**Closed** 2018-05-15 15:25 UTC
