### ISSUE TITLE
Array recursion

### ISSUE THREAD

**Issue by hobbeshunter** [Level-2/Transphporm#79] opened 2016-04-12 15:49 UTC
Sorry for bothering you again, but I can't get it to work. As soon as I modify your nav test to use an object with a method to return the data, it's failing.

Cheers

**Comment by hobbeshunter** [comment] 2016-04-18 15:28
I made a small unit test to show what I think should be supported.

https://github.com/hobbeshunter/Transphporm/tree/template-recursion-dev

**Comment by hobbeshunter** [comment] 2016-06-25 11:09
@TomBZombie even with the new parser, it's not working. When I try to do array recursion with a data object and a function call, I get following errors:
```
Warning
: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in
/var/www/html/eckblick/eckframe/trunk/vendor/level-2/transphporm/src/Parser/ValueData.php
on line 45

Notice
: Array to string conversion in
/var/www/html/eckblick/eckframe/trunk/vendor/level-2/transphporm/src/Parser/ValueResult.php
on line 38

Warning
: Invalid argument supplied for foreach() in
/var/www/html/eckblick/eckframe/trunk/vendor/level-2/transphporm/src/Property/Repeat.php
on line 22
```

To mime an recursive function call I suggest to explicitly add the wanted data to the template call.
```
content: template('nav.xml', '', 'nav.tss', iteration(children) );
```

**Comment by TomBZombie** [comment] 2016-06-25 13:37
can you paste the unit test here? You should be able to also use 

```content: template('nav.xml', '', 'nav.tss'); bind: iteration(children);```

for this result

**Comment by hobbeshunter** [comment] 2016-06-26 12:47
```php
public function testNestedDataFromObject() {
		$data = new Foo();

		$template = new \Transphporm\Builder(__DIR__ . '/nav.xml', __DIR__ . '/nav2.tss');

		 $this->assertEquals($this->stripTabs('<ul>
				<li>
					<a href="Parent">Parent</a>
					<ul>
						<li>
							<a href="Child 2">Child 2</a>
							<ul>
								<li>
									<a href="two.1">grandchild 1</a>
								</li>
								<li>
									<a href="two.2">grandchildchild 2</a>
								</li>
							</ul>
						</li>
						<li>
							<a href="child 1">child 1</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="http://facebook.com">Facebook</a>
				</li>
		</ul>'), $this->stripTabs($template->output($data)->body));
	}

class Foo {

	public function returnNestedData() {
		return json_decode('{ "children": [
			{
			"target":"Parent",
			"title":"Parent",
			"children":
			[
			{
				"target":"Child 2",
				"title":"Child 2",
				"children":
					[
						{
							 "target":"two.1",
							 "title":"grandchild 1"
						 },
						 {
							 "target":"two.2",
							 "title":"grandchildchild 2"
						 }
					 ]
				},
				{
			"target":"child 1",
			"title":"child 1"
			}
			]
			},
			{
			"target":"http://facebook.com",
			"title":"Facebook"
			}
			]}', true);
	}
}
```

and nav2.tss:
```css
ul li {repeat: data(returnNestedData().children); bind: iteration())}
ul li:iteration[children]:after {content: template('nav.xml', '', 'nav2.tss'); }

ul li a:attr(href) {content: iteration(target);}
ul li a {content: iteration(title);}
```

**Comment by solleer** [comment] 2016-06-27 01:44
The problem is that it takes the data from `returnNestedData().children` and tries to run that function on it
if you change this
```css
ul li:iteration[children]:after {content: template('nav.xml', '', 'nav2.tss'); }
```
to
```css
ul li:iteration[children]:after {content: template('nav.xml', '', 'nav.tss'); }
```

**Comment by hobbeshunter** [comment] 2016-06-28 13:58
Alright, I see. So the way data is provided changes from the first recursion step to the second. But that way we need 2 different .tss files. Don't you think 
```
content: template('nav.xml', '', 'nav.tss', iteration(children) );
```
would be the cleanest and easiest to understand?

**Comment by solleer** [comment] 2016-06-29 02:11
I like using the bind property since it is already built in

**Comment by solleer** [comment] 2016-08-05 04:43
Can this be closed?

**Comment by solleer** [comment] 2016-08-05 13:56
I'm going to close this since all the tests pass about it

**Closed by solleer** 2016-08-05 13:56 UTC
Labels: bug
